# docker-compose.dev.yml
version: '3.9'

services:
  web:
    build:
      context: ./vide-grenier-dev
      dockerfile: Dockerfile
    container_name: dev-phpapache
    ports:
      - "1337:80"
    environment:
      ALLOW_OVERRIDE: 'true'
      user: 'root'
      db: 'mariadb'
      password: 'root'
      host: 'db'
    volumes:
      - ./vide-grenier-dev:/var/www/html
    depends_on:
      - db
      - node

  pma:
    image: phpmyadmin
    container_name: dev-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    links:
      - db:db

  db:
    image: mariadb:latest
    container_name: dev-mysql
    ports:
      - "3306:3306"
    volumes:
      - dev-db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: videgrenierenligne_dev
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T

  node:
    image: node:14
    container_name: dev-node
    working_dir: /var/www/html
    volumes:
      - ./vide-grenier-dev:/var/www/html
    command: sh -c "npm install && npm run watch"
    depends_on:
      - db

volumes:
  dev-db-data:
