version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: stage  # Specify the branch for stage
    container_name: stage-phpapache
    ports:
      - "1338:80"
    environment:
      ALLOW_OVERRIDE: 'true'
      user: 'root'
      DB_NAME: videgrenierenligne_stage
      DB_USER: webapplication
      DB_PASSWORD: 653rag9T
      DB_HOST: db
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - node
    networks:
      - stage-network

  pma:
    image: phpmyadmin
    container_name: stage-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - stage-network

  db:
    image: mariadb:latest
    container_name: stage-mysql
    ports:
      - "3307:3306"
    volumes:
      - stage-db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: videgrenierenligne_stage
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    networks:
      - stage-network

  node:
    image: node:14
    container_name: stage-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run watch"
    depends_on:
      - db
    networks:
      - stage-network

volumes:
  stage-db-data:

networks:
  stage-network:
