version: '3.9'

services:
  web:
    image: php7.4-apache:projet
    container_name: videgrenier-phpapache
    ports:
      # local:container
      - "1337:80"
    environment: 
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: videgrenierenligne
        MYSQL_USER: webapplication
        MYSQL_PASSWORD: 653rag9T
      
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    # command: sh -c "npm install && npm run watch"

  pma:
    image: phpmyadmin
    container_name: videgrenier-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    links:
      - db:db

  db:
    image: mariadb:latest
    container_name: projet-mysql
    ports:
      - "3306:3306"
    volumes:
      # Volume de la base de données
      - ./db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T

