version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH: Feature-Env2  # Specify the branch for Env2
        GITHUB_TOKEN: ${GITHUB_TOKEN}  # Use the environment variable
    container_name: env2-phpapache
    ports:
      - "1338:80"
    environment:
      ALLOW_OVERRIDE: 'true'
      user: 'root'
      db: 'mariadb'
      password: 'root' 
      host: 'db'
    volumes:
      - ./src-env2:/var/www/html
    depends_on:
      - db
      - node

  pma:
    image: phpmyadmin
    container_name: env2-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 1024M
    ports:
      - "8081:80"
    links:
      - db:db
  
  db:
    image: mariadb:latest
    container_name: env2-mysql
    ports:
      - "3307:3306"
    volumes:
      - env2-db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: videgrenierenligne_env2
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T

  node:
    image: node:14
    container_name: env2-node
    working_dir: /var/www/html
    volumes:
      - ./src-env2:/var/www/html
    command: sh -c "npm install && npm run watch"
    depends_on:
      - db

volumes:
  env2-db-data:
